import type { Metadata } from "next";
import "./globals.css";
// 클라이언트 컴포넌트 임포트
import ClientLayout from "./ClientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>{/* 여기에 메타태그나 스크립트를 넣을 수 있습니다 */}</head>
      <body
        style={{ margin: 0, padding: 0, height: "100vh", overflow: "hidden" }}
      >
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
